service: friendly-funicular
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1  
  deploymentBucket:
    name: cohort2.serverless.deploys

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
    environment:
      ACCESS_INFORMATION: '34234'
      ACCESS_KEY: ${ssm:ACCESS_KEY}

plugins:
  - serverless-offline
